# extends:
#   - standard-with-typescript
#   - prettier
# ignorePatterns:
#   - node_modules
#   - dist
# rules:
#   import/order:
#     - error
#     - alphabetize:
#         order: asc
#         caseInsensitive: false
#         orderImportKind: asc
#   '@typescipt-eslint/consistent-type-definitions':
#     - error
#     - type
#   '@typescipt-eslint/strict-boolean-expressions': off
#   '@typescipt-eslint/prefer-nullish-coalescing': off
#   '@typescipt-eslint/explicit-function-return-type': off
#   # '@typescipt-eslint/restrict-template-expressions': off
#   '@typescipt-eslint/triple-slash-reference': off
#   '@typescipt-eslint/ban-types': off
#   '@typescipt-eslint/consistent-type-assertions': off
#   jsx-a11y/anchor-is-valid: off
#   curly:
#     - error
#     - all
#   no-irregular-whitespace:
#     - error
#     - skipTemplates: true
#     - skipStrings: true
#   no-console:
#     - error
#     - allow:
#         - info
#         - error
#         - warn
